version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=mssql;Database=TaskManagementAPI;User Id=sa;Password=YourStrongPassword123;Encrypt=false;Trusted_Connection=False"
    depends_on:
      - mssql
    networks:
      - mynetwork

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrongPassword123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
